# Generated by Django 4.2.13 on 2024-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_tournament_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='sports',
            field=models.CharField(default='Select any', max_length=200),
        ),
    ]
