# Generated by Django 4.2.13 on 2024-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournaments_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='sports',
        ),
        migrations.AddField(
            model_name='tournaments',
            name='sports',
            field=models.ManyToManyField(related_name='tournaments', to='tournaments.sport'),
        ),
    ]
